import { StadiumLocations } from '../types';

// Stadium locations for NFL and CFB teams
export const stadiumLocations: StadiumLocations = {
  // NFL Teams
  'Arizona Cardinals': 'Glendale, AZ',
  'Atlanta Falcons': 'Atlanta, GA',
  'Baltimore Ravens': 'Baltimore, MD',
  'Buffalo Bills': 'Orchard Park, NY',
  'Carolina Panthers': 'Charlotte, NC',
  'Chicago Bears': 'Chicago, IL',
  'Cincinnati Bengals': 'Cincinnati, OH',
  'Cleveland Browns': 'Cleveland, OH',
  'Dallas Cowboys': 'Arlington, TX',
  'Denver Broncos': 'Denver, CO',
  'Detroit Lions': 'Detroit, MI',
  'Green Bay Packers': 'Green Bay, WI',
  'Houston Texans': 'Houston, TX',
  'Indianapolis Colts': 'Indianapolis, IN',
  'Jacksonville Jaguars': 'Jacksonville, FL',
  'Kansas City Chiefs': 'Kansas City, MO',
  'Las Vegas Raiders': 'Las Vegas, NV',
  'Los Angeles Chargers': 'Inglewood, CA',
  'Los Angeles Rams': 'Inglewood, CA',
  'Miami Dolphins': 'Miami Gardens, FL',
  'Minnesota Vikings': 'Minneapolis, MN',
  'New England Patriots': 'Foxborough, MA',
  'New Orleans Saints': 'New Orleans, LA',
  'New York Giants': 'East Rutherford, NJ',
  'New York Jets': 'East Rutherford, NJ',
  'Philadelphia Eagles': 'Philadelphia, PA',
  'Pittsburgh Steelers': 'Pittsburgh, PA',
  'San Francisco 49ers': 'Santa Clara, CA',
  'Seattle Seahawks': 'Seattle, WA',
  'Tampa Bay Buccaneers': 'Tampa, FL',
  'Tennessee Titans': 'Nashville, TN',
  'Washington Commanders': 'Landover, MD',
  
  // CFB Teams (major programs)
  'Alabama': 'Tuscaloosa, AL',
  'Ohio State': 'Columbus, OH',
  'Georgia': 'Athens, GA',
  'Michigan': 'Ann Arbor, MI',
  'Texas': 'Austin, TX',
  'Oklahoma': 'Norman, OK',
  'USC': 'Los Angeles, CA',
  'Penn State': 'State College, PA',
  'LSU': 'Baton Rouge, LA',
  'Florida': 'Gainesville, FL',
  'Notre Dame': 'South Bend, IN',
  'Clemson': 'Clemson, SC',
  'Texas A&M': 'College Station, TX',
  'Auburn': 'Auburn, AL',
  'Oregon': 'Eugene, OR',
  'Florida State': 'Tallahassee, FL',
  'Tennessee': 'Knoxville, TN',
  'Ole Miss': 'Oxford, MS',
  'Mississippi State': 'Starkville, MS',
  'Arkansas': 'Fayetteville, AR',
  'Kentucky': 'Lexington, KY',
  'South Carolina': 'Columbia, SC',
  'Missouri': 'Columbia, MO',
  'Vanderbilt': 'Nashville, TN',
  'TCU': 'Fort Worth, TX',
  'Baylor': 'Waco, TX',
  'Oklahoma State': 'Stillwater, OK',
  'Kansas State': 'Manhattan, KS',
  'Kansas': 'Lawrence, KS',
  'Iowa State': 'Ames, IA',
  'West Virginia': 'Morgantown, WV',
  'Iowa': 'Iowa City, IA',
  'Wisconsin': 'Madison, WI',
  'Nebraska': 'Lincoln, NE',
  'Minnesota': 'Minneapolis, MN',
  'Northwestern': 'Evanston, IL',
  'Purdue': 'West Lafayette, IN',
  'Illinois': 'Champaign, IL',
  'Indiana': 'Bloomington, IN',
  'Rutgers': 'Piscataway, NJ',
  'Maryland': 'College Park, MD',
  'Michigan State': 'East Lansing, MI',
  'Washington': 'Seattle, WA',
  'UCLA': 'Pasadena, CA',
  'Stanford': 'Stanford, CA',
  'California': 'Berkeley, CA',
  'Arizona': 'Tucson, AZ',
  'Arizona State': 'Tempe, AZ',
  'Colorado': 'Boulder, CO',
  'Utah': 'Salt Lake City, UT',
  'Oregon State': 'Corvallis, OR',
  'Washington State': 'Pullman, WA',
  'NC State': 'Raleigh, NC',
  'North Carolina': 'Chapel Hill, NC',
  'Duke': 'Durham, NC',
  'Virginia': 'Charlottesville, VA',
  'Virginia Tech': 'Blacksburg, VA',
  'Miami': 'Miami Gardens, FL',
  'Georgia Tech': 'Atlanta, GA',
  'Louisville': 'Louisville, KY',
  'Pittsburgh': 'Pittsburgh, PA',
  'Syracuse': 'Syracuse, NY',
  'Boston College': 'Chestnut Hill, MA',
  'Wake Forest': 'Winston-Salem, NC',
  'SMU': 'Dallas, TX',
  'Tulane': 'New Orleans, LA',
  'Memphis': 'Memphis, TN',
  'Navy': 'Annapolis, MD',
  'Army': 'West Point, NY',
  'Air Force': 'Colorado Springs, CO',
  'BYU': 'Provo, UT',
  'UCF': 'Orlando, FL',
  'Cincinnati': 'Cincinnati, OH',
  'Houston': 'Houston, TX',
  'Boise State': 'Boise, ID',
  'San Diego State': 'San Diego, CA',
  'Fresno State': 'Fresno, CA',
  'Air Force': 'Colorado Springs, CO',
  'Akron': 'Akron, OH',
  'Appalachian State': 'Boone, NC',
  'Arkansas State': 'Jonesboro, AR',
  'Ball State': 'Muncie, IN',
  'Bowling Green': 'Bowling Green, OH',
  'Buffalo': 'Buffalo, NY',
  'California': 'Berkeley, CA',
  'Central Michigan': 'Mount Pleasant, MI',
  'Charlotte': 'Charlotte, NC',
  'Coastal Carolina': 'Conway, SC',
  'Colorado State': 'Fort Collins, CO',
  'East Carolina': 'Greenville, NC',
  'Eastern Michigan': 'Ypsilanti, MI',
  'Florida Atlantic': 'Boca Raton, FL',
  'Florida International': 'Miami, FL',
  'Georgia Southern': 'Statesboro, GA',
  'Georgia State': 'Atlanta, GA',
  'Hawaii': 'Honolulu, HI',
  'James Madison': 'Harrisonburg, VA',
  'Kent State': 'Kent, OH',
  'Liberty': 'Lynchburg, VA',
  'Louisiana': 'Lafayette, LA',
  'Louisiana Monroe': 'Monroe, LA',
  'Louisiana Tech': 'Ruston, LA',
  'Marshall': 'Huntington, WV',
  'Miami (OH)': 'Oxford, OH',
  'Middle Tennessee': 'Murfreesboro, TN',
  'Nevada': 'Reno, NV',
  'New Mexico': 'Albuquerque, NM',
  'New Mexico State': 'Las Cruces, NM',
  'North Texas': 'Denton, TX',
  'Northern Illinois': 'DeKalb, IL',
  'Ohio': 'Athens, OH',
  'Old Dominion': 'Norfolk, VA',
  'Rice': 'Houston, TX',
  'San Jose State': 'San Jose, CA',
  'South Alabama': 'Mobile, AL',
  'South Florida': 'Tampa, FL',
  'Southern Mississippi': 'Hattiesburg, MS',
  'Temple': 'Philadelphia, PA',
  'Texas State': 'San Marcos, TX',
  'Texas Tech': 'Lubbock, TX',
  'Toledo': 'Toledo, OH',
  'Troy': 'Troy, AL',
  'Tulsa': 'Tulsa, OK',
  'UAB': 'Birmingham, AL',
  'UConn': 'East Hartford, CT',
  'UMass': 'Amherst, MA',
  'UNLV': 'Las Vegas, NV',
  'Utah State': 'Logan, UT',
  'UTEP': 'El Paso, TX',
  'UTSA': 'San Antonio, TX',
  'Western Kentucky': 'Bowling Green, KY',
  'Western Michigan': 'Kalamazoo, MI',
  'Wyoming': 'Laramie, WY',
};

// Team aliases - maps alternative names to official team names
export const teamAliases: { [key: string]: string } = {
  // CFB Common Aliases
  'UT': 'Texas',
  'Texas Longhorns': 'Texas',
  'Alabama Crimson Tide': 'Alabama',
  'Ohio State Buckeyes': 'Ohio State',
  'Georgia Bulldogs': 'Georgia',
  'UGA': 'Georgia',
  'Michigan Wolverines': 'Michigan',
  'Oklahoma Sooners': 'Oklahoma',
  'OU': 'Oklahoma',
  'USC Trojans': 'USC',
  'Penn State Nittany Lions': 'Penn State',
  'PSU': 'Penn State',
  'LSU Tigers': 'LSU',
  'Florida Gators': 'Florida',
  'UF': 'Florida',
  'Notre Dame Fighting Irish': 'Notre Dame',
  'Clemson Tigers': 'Clemson',
  'Texas A&M Aggies': 'Texas A&M',
  'TAMU': 'Texas A&M',
  'Auburn Tigers': 'Auburn',
  'Oregon Ducks': 'Oregon',
  'UO': 'Oregon',
  'Florida State Seminoles': 'Florida State',
  'FSU': 'Florida State',
  'Tennessee Volunteers': 'Tennessee',
  'Mississippi': 'Ole Miss',
  'Ole Miss Rebels': 'Ole Miss',
  'Mississippi State Bulldogs': 'Mississippi State',
  'Arkansas Razorbacks': 'Arkansas',
  'Kentucky Wildcats': 'Kentucky',
  'South Carolina Gamecocks': 'South Carolina',
  'Missouri Tigers': 'Missouri',
  'Mizzou': 'Missouri',
  'Vanderbilt Commodores': 'Vanderbilt',
  'TCU Horned Frogs': 'TCU',
  'Baylor Bears': 'Baylor',
  'Oklahoma State Cowboys': 'Oklahoma State',
  'Kansas State Wildcats': 'Kansas State',
  'KSU': 'Kansas State',
  'Kansas Jayhawks': 'Kansas',
  'KU': 'Kansas',
  'Iowa State Cyclones': 'Iowa State',
  'ISU': 'Iowa State',
  'West Virginia Mountaineers': 'West Virginia',
  'WVU': 'West Virginia',
  'Iowa Hawkeyes': 'Iowa',
  'Wisconsin Badgers': 'Wisconsin',
  'Nebraska Cornhuskers': 'Nebraska',
  'Minnesota Golden Gophers': 'Minnesota',
  'Northwestern Wildcats': 'Northwestern',
  'Purdue Boilermakers': 'Purdue',
  'Illinois Fighting Illini': 'Illinois',
  'Indiana Hoosiers': 'Indiana',
  'IU': 'Indiana',
  'Rutgers Scarlet Knights': 'Rutgers',
  'Maryland Terrapins': 'Maryland',
  'UMD': 'Maryland',
  'Michigan State Spartans': 'Michigan State',
  'MSU': 'Michigan State',
  'Washington Huskies': 'Washington',
  'UW': 'Washington',
  'UCLA Bruins': 'UCLA',
  'Stanford Cardinal': 'Stanford',
  'California Golden Bears': 'California',
  'Cal': 'California',
  'Arizona Wildcats': 'Arizona',
  'UA': 'Arizona',
  'Arizona State Sun Devils': 'Arizona State',
  'ASU': 'Arizona State',
  'Colorado Buffaloes': 'Colorado',
  'CU': 'Colorado',
  'Utah Utes': 'Utah',
  'Oregon State Beavers': 'Oregon State',
  'OSU': 'Oregon State',
  'Washington State Cougars': 'Washington State',
  'WSU': 'Washington State',
  'NC State Wolfpack': 'NC State',
  'NCSU': 'NC State',
  'North Carolina Tar Heels': 'North Carolina',
  'UNC': 'North Carolina',
  'Duke Blue Devils': 'Duke',
  'Virginia Cavaliers': 'Virginia',
  'UVA': 'Virginia',
  'Virginia Tech Hokies': 'Virginia Tech',
  'VT': 'Virginia Tech',
  'Miami Hurricanes': 'Miami',
  'The U': 'Miami',
  'UM': 'Miami',
  'Georgia Tech Yellow Jackets': 'Georgia Tech',
  'GT': 'Georgia Tech',
  'Louisville Cardinals': 'Louisville',
  'Pittsburgh Panthers': 'Pittsburgh',
  'Pitt': 'Pittsburgh',
  'Syracuse Orange': 'Syracuse',
  'Boston College Eagles': 'Boston College',
  'BC': 'Boston College',
  'Wake Forest Demon Deacons': 'Wake Forest',
  'SMU Mustangs': 'SMU',
  'Tulane Green Wave': 'Tulane',
  'Memphis Tigers': 'Memphis',
  'Navy Midshipmen': 'Navy',
  'Army Black Knights': 'Army',
  'Air Force Falcons': 'Air Force',
  'BYU Cougars': 'BYU',
  'UCF Knights': 'UCF',
  'Cincinnati Bearcats': 'Cincinnati',
  'Houston Cougars': 'Houston',
  'UH': 'Houston',
  'Boise State Broncos': 'Boise State',
  'San Diego State Aztecs': 'San Diego State',
  'SDSU': 'San Diego State',
  'Fresno State Bulldogs': 'Fresno State',
  'Hawaii Rainbow Warriors': 'Hawaii',
  'Hawai\'i Rainbow Warriors': 'Hawaii',
  'Texas Tech Red Raiders': 'Texas Tech',
  'TTU': 'Texas Tech',
  'UTSA Roadrunners': 'UTSA',
  'UTEP Miners': 'UTEP',
  'Texas State Bobcats': 'Texas State',
  'North Texas Mean Green': 'North Texas',
  'UNT': 'North Texas',
  'Rice Owls': 'Rice',
  'JMU': 'James Madison',
  'James Madison Dukes': 'James Madison',
  'App State': 'Appalachian State',
  'Appalachian State Mountaineers': 'Appalachian State',
  'Coastal Carolina Chanticleers': 'Coastal Carolina',
  'Louisiana Ragin Cajuns': 'Louisiana',
  'ULL': 'Louisiana',
  'Louisiana Lafayette': 'Louisiana',
  'ULM': 'Louisiana Monroe',
  'Louisiana Monroe Warhawks': 'Louisiana Monroe',
  'Louisiana Tech Bulldogs': 'Louisiana Tech',
  'Southern Miss': 'Southern Mississippi',
  'Southern Miss Golden Eagles': 'Southern Mississippi',
  'USM': 'Southern Mississippi',
  'South Alabama Jaguars': 'South Alabama',
  'USA': 'South Alabama',
  'South Florida Bulls': 'South Florida',
  'USF': 'South Florida',
  'FAU': 'Florida Atlantic',
  'Florida Atlantic Owls': 'Florida Atlantic',
  'FIU': 'Florida International',
  'Florida International Panthers': 'Florida International',
  'East Carolina Pirates': 'East Carolina',
  'ECU': 'East Carolina',
  'Marshall Thundering Herd': 'Marshall',
  'Old Dominion Monarchs': 'Old Dominion',
  'ODU': 'Old Dominion',
  'Charlotte 49ers': 'Charlotte',
  'Georgia Southern Eagles': 'Georgia Southern',
  'Georgia State Panthers': 'Georgia State',
  'Troy Trojans': 'Troy',
  'UAB Blazers': 'UAB',
  'Middle Tennessee Blue Raiders': 'Middle Tennessee',
  'MTSU': 'Middle Tennessee',
  'Western Kentucky Hilltoppers': 'Western Kentucky',
  'WKU': 'Western Kentucky',
  'UMass Minutemen': 'UMass',
  'UConn Huskies': 'UConn',
  'Connecticut': 'UConn',
  'Liberty Flames': 'Liberty',
  'Akron Zips': 'Akron',
  'Ball State Cardinals': 'Ball State',
  'Bowling Green Falcons': 'Bowling Green',
  'BGSU': 'Bowling Green',
  'Buffalo Bulls': 'Buffalo',
  'Central Michigan Chippewas': 'Central Michigan',
  'CMU': 'Central Michigan',
  'Eastern Michigan Eagles': 'Eastern Michigan',
  'EMU': 'Eastern Michigan',
  'Kent State Golden Flashes': 'Kent State',
  'Miami RedHawks': 'Miami (OH)',
  'Miami OH': 'Miami (OH)',
  'Northern Illinois Huskies': 'Northern Illinois',
  'NIU': 'Northern Illinois',
  'Ohio Bobcats': 'Ohio',
  'Toledo Rockets': 'Toledo',
  'Western Michigan Broncos': 'Western Michigan',
  'WMU': 'Western Michigan',
  'Colorado State Rams': 'Colorado State',
  'CSU': 'Colorado State',
  'Nevada Wolf Pack': 'Nevada',
  'New Mexico Lobos': 'New Mexico',
  'UNM': 'New Mexico',
  'New Mexico State Aggies': 'New Mexico State',
  'NMSU': 'New Mexico State',
  'San Jose State Spartans': 'San Jose State',
  'SJSU': 'San Jose State',
  'UNLV Rebels': 'UNLV',
  'Utah State Aggies': 'Utah State',
  'USU': 'Utah State',
  'Wyoming Cowboys': 'Wyoming',
  'Arkansas State Red Wolves': 'Arkansas State',
  'A-State': 'Arkansas State',
  'Temple Owls': 'Temple',
  'Tulsa Golden Hurricane': 'Tulsa',
};

export const getStadiumLocation = (teamName: string): string => {
  // Check alias first
  const officialName = teamAliases[teamName];
  if (officialName && stadiumLocations[officialName]) {
    return stadiumLocations[officialName];
  }
  
  // Exact match
  if (stadiumLocations[teamName]) {
    return stadiumLocations[teamName];
  }
  
  // Partial match
  for (const [team, location] of Object.entries(stadiumLocations)) {
    if (teamName.includes(team) || team.includes(teamName)) {
      return location;
    }
  }
  
  return 'Location Unknown';
};

export const getTeamInitials = (teamName: string): string => {
  const words = teamName.split(' ').filter(word => 
    !['the', 'of', 'and'].includes(word.toLowerCase())
  );
  
  if (words.length >= 2) {
    return (words[0][0] + words[words.length - 1][0]).toUpperCase();
  }
  return teamName.substring(0, 2).toUpperCase();
};

export const truncateTeamName = (name: string): string => {
  name = name.replace(/(Crimson Tide|Buckeyes|Bulldogs|Wolverines|Longhorns|Sooners|Trojans|Fighting Irish|Tigers|Gators|Seminoles|Aggies|Ducks|Nittany Lions)/gi, '');
  name = name.trim();
  
  return name.length > 18 ? name.substring(0, 16) + '...' : name;
};
